### PR TITLE
remove FetchEvent, HIDInputReportEvent and TimeEvent

### PR DESCRIPTION
**Pull request by FredericHeem**

### CODE REVIEW

**Review by louwers — CHANGES_REQUESTED** [review]
The `EventListener` type is identical to `(event: any) => any`.

It should be replaced with that.

**Comment by FredericHeem** [comment]
The types which has been removed from the union were any, The EventListener should be correct with this PR

**Comment by louwers** [comment]
Hmm for me it still shows as `any`.

But I think there is very little value in such a large union, because you need to type cast anyway to do anything useful with these types.

**Comment by FredericHeem** [comment]
`EventListener` is no longer `(event: any) => any`.

Screenshot 2024-09-13 at 17 56 46

**Pull request merged**
